### ISSUE TITLE
add a GH action that updates the copyright year

### ISSUE THREAD

**Issue by LeonBrands** [Rythe-Interactive/Legion-LLRI#76]
**Is your feature request related to a problem? Please describe.**
Copyright is described on a per-file basis, with a starting and current year - A GitHub action should keep the current year updated by running on a yearly basis.

**Describe the solution you'd like**
Integrate https://github.com/FantasticFiasco/action-update-license-year into the repo's actions, configured in such a way that it checks every source file for the copyright notice.

**Comment by GlynLeine** [comment]
You might wanna look at this:
https://github.com/Rythe-Interactive/Legion-Engine/tree/task/automated-copyright-headers
should prolly be able to adapt it to increment the year too
